### ISSUE TITLE
Which tokenizer has been used for the 200K dataset?

### ISSUE THREAD

**Issue by rattle99** [Sripaad/ai4privacy#3]
Which tokenizer from the BERT family has been used to generate the and split the text into tokens in the `tokenised_text` column in the dataset -> [link](https://huggingface.co/datasets/ai4privacy/pii-masking-200k)

It is mentioned in the readme that 
> "tokenised_text" breaks down the unmasked sentence into tokens using Bert Family tokeniser to help fine-tune large language models.

But, the vocabulary used possibly has minor differences when compared to the huggingface BERT tokeniser used with:
`BertTokenizer.from_pretrained("bert-base-cased")`

**Comment by MikeDoes** [comment]
distillbert

**Comment by rattle99** [comment]
> distillbert

It's not distilbert, since the tokenisation has minor differences when tested. It could be mbert. Seeking a confirmation from the authors.

**Comment by Sripaad** [comment]
Hi @rattle99 its `distilbert/distilbert-base-multilingual-cased`.
